### ISSUE TITLE
TODO: Show a warning if no configuration file is found 

### ISSUE THREAD

**Issue by L-TChen** [agda/fix-whitespace#1]
As title.

**Comment by MatthewDaggitt** [comment]
I think it would be good if it could show a warning, but then fall back to the behaviour of the old implementation i.e. check every `.agda` and `.md` it finds under the current directory.

**Comment by L-TChen** [comment]
The original implementation does not really check every `.agda` or `.md` under the current directory, as there are some exceptions to avoid. 

What I plan to do is to make it more like a unix command-line tool — either you can specify files to check/fix by glob or use a configuration file like what it does now. If none of them is specified, then it gives a brief description. Does it sound better?

**Comment by L-TChen** [comment]
Closed by https://github.com/agda/fix-whitespace/commit/f5f5ea4bf7bce03e2a049366f531985216e3982e.
