### ISSUE TITLE
Release new version supporting GHC 8.10.7

### ISSUE THREAD

**Issue by asr** [agda/fix-whitespace#25]
Can someone make the release? If someone add me as maintainer in Hackage (user `AndresSicardRamirez`) I could make the release.

**Comment by andreasabel** [comment]
You already are, I added you as maintainer from the start!  https://hackage.haskell.org/package/fix-whitespace/maintainers/

**Comment by asr** [comment]
Done! (https://hackage.haskell.org/package/fix-whitespace-0.0.7)

**Comment by andreasabel** [comment]
Installed it from hackage with GHC 9.0.1.  
Compilation time: 10min (thanks to v2-cabal, all dependencies were rebuilt).
