### ISSUE TITLE
`--check` should be the default, option `--fix` should touch files

### ISSUE THREAD

**Issue by andreasabel** [agda/fix-whitespace#28]
`--check` should be the default, option `--fix` should fix the whitespace issues in files.  
This is the safer UI.

**Comment by L-TChen** [comment]
I agree that it makes this command safer, but it is not expected for common commands. For example, `rm` and `mv` are (very) unsafe, but their default behaviour is to do something that cannot be undone even without any warning. You also need a configuration file to run, otherwise it just does nothing.

**Comment by andreasabel** [comment]
> For example, `rm` and `mv` are (very) unsafe, but their default behaviour is to do something that cannot be undone even without any warning.

I'd say these two commands are kind of _atomic_ commands whose effect is very predictable.  In contrast, `fix-whitespace` does an analysis first.  Usually, I would like to see the action plan based on the analysis first before committing to it.

I see two main uses of `fix-whitespace`:
1. In batch mode (like the Agda Makefile):  There, one would many `--fix` directly, but writing an extra `--fix` in a batch file is zero overhead.
2. Interactively.  There, I would usually be careful and `--check` first, maybe make some adjustments, `--check` again, and finally `--fix`.  

So the default `--check` looks more sensible to me.

**Comment by andreasabel** [comment]
Anyway, there is no consensus, so let's keep the status-quo for now.

**Comment by ulysses4ever** [comment]
I don't have objective data to back my opinion, but, FWIW, I too feel better about the non-destructive mode (`--check`) as the default. A single counterpoint I can think of is the name of the tool itself: it has `fix` right in its name, so, perhaps, one would expect the destructive update as the default, indeed.
