### ISSUE TITLE
Fix trailing tabs, too.

### ISSUE THREAD

**Issue by bionade24** [agda/fix-whitespace#42]
Fix tabs that lurk around, also in empty lines, too.

**Comment by andreasabel** [comment]
Yes, we do, don't we?
https://github.com/agda/fix-whitespace/blob/e593b4adb928fc3815de2deade87e0c1d1d093e2/FixWhitespace.hs#L260-L268

**Comment by bionade24** [comment]
From my bare understanding of the Haskell Code, it only removes trailing tabs if tabs get converted to spaces beforehand. I ran it with `--tabs=0`. If it's not the case,  an example file it doesn't remove tabs on empty lines & trailing tabs is: https://github.com/bionade24/Realtek-rts5229-linux-driver/blob/master/rtsx.h

**Comment by andreasabel** [comment]
Right, that likely got broken when the `--tabs` flag was added.
Thanks, hasn't occurred to me!

**Comment by andreasabel** [comment]
This is being released as v0.0.11, in time for Nikolaus 2022. ;-)
Binaries should appear here: https://github.com/agda/fix-whitespace/releases/tag/v0.0.11

**Comment by andreasabel** [comment]
Ooops, forgot Hackage release, done now.
