### ISSUE TITLE
unknown package: filepattern

### ISSUE THREAD

**Issue by gallais** [agda/fix-whitespace#6]
Even after running `cabal update`, I keep getting an error telling me that
`filepattern` is an unknown package.

> [__1] unknown package: filepattern (dependency of fix-whitespace)

**Comment by gallais** [comment]
This error should probably be transferred to agda/agda (there is a magic button
in the column on the right hand side): I now believe this is a problem with the
`Makefile` issuing the command

```
$(CABAL_CMD) $(CABAL_BUILD_CMD)
```

without first installing the package's dependencies.

**Comment by EdNutting** [comment]
Interestingly, this issue wasn't picked up by any of Agda's CI builds since none of them use the Makefile. It may be worth creating an issue on Agda to that effect.
